FROM gradle:8.5-jdk17-alpine AS builder

WORKDIR /app

COPY gradlew .

COPY gradle ./gradle

COPY  build.gradle  settings.gradle ./

RUN ./gradlew dependencies --no-daemon

COPY src ./src

RUN ./gradlew bootJar --no-daemon

FROM eclipse-temurin:17-jre-alpine

WORKDIR /app

ARG JAR_FILE=build/libs/*.jar

COPY --from=builder /app/${JAR_FILE} app.jar

EXPOSE 8080

ENTRYPOINT ["java","-jar","app.jar"]